export const START_LOGIN ="START_LOGIN"
export const LOGIN_SUCCESS ="LOGIN_SUCCESS"
export const LOGIN_FAILD = "LOGIN_FAILD";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE"
export const CHANGE_CURRENT_PAGE_NAME = "CHANGE_CURRENT_PAGE_NAME";
export const SAVE_USER_PERMISSIONS = "SAVE_USER_PERMISSIONS";
export const ALERT_MESSAGE = "ALERT_MESSAGE"